spring:
  profiles:
    active: Dev
---
spring:
  profiles: Dev
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8099
debug: true
application:
  queueOut: movieQueue
  movieLocation : C:/movie
---
spring:
