spring:
  profiles:
    active: Dev
---
spring:
  profiles: Dev
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8099
debug: true
app:
  movieQueue: movieQueue
  movieLocation : C:\movie
rabbit:
  host: localhost
  port: 5672
  username: docker
  password: docker
  numberThread: 1
logging:
  level:
    org.springframework.web: ERROR
    com.hac.*: DEBUG
---
spring:
  profiles: Docker
  http:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
server:
  port: ${SEVER_PORT}
debug: false
app:
  movieQueue: ${MOVIE_QUEUE}
  movieLocation : ${MOVIE_LOCATION}
rabbit:
  host: ${RABBIT_HOST}
  port: ${RABBIT_PORT}
  username: ${RABBIT_USERNAME}
  password: ${RABBIT_PASSWORD}
logging:
  level:
    org.springframework.web: ERROR
    com.hac.*: ERROR

