spring:
  profiles:
    active: Dev
---
spring:
  profiles: Dev
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8099
debug: true
app:
  movieQueue: movieQueue
  movieLocation : C:/movie
rabbit:
  host: localhost
  port: 5672
  username: docker
  password: docker
---
spring:

